//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace purchasesPMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_Items
    {
        public int purchase_id { get; set; }
        public int prod_id { get; set; }
        public Nullable<int> Batch_NO { get; set; }
        public Nullable<int> Unit_id { get; set; }
        public decimal Net_price { get; set; }
        public int quantity { get; set; }
        public decimal totalprice { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<int> deliver_qauntity { get; set; }
        public Nullable<System.DateTime> expire_date { get; set; }
        public Nullable<decimal> tax { get; set; }
    
        public virtual TB_PRODUCTS TB_PRODUCTS { get; set; }
        public virtual TB_PURCHASES TB_PURCHASES { get; set; }
        public virtual TB_UNITES TB_UNITES { get; set; }
    }
}
