//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace purchasesPMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchases_view
    {
        public int purchase_id { get; set; }
        public string cur_name { get; set; }
        public decimal tax { get; set; }
        public string payment_Notes { get; set; }
        public string purchase_Notes { get; set; }
        public string purchase_status { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public Nullable<decimal> TOTAL_PAIED { get; set; }
        public Nullable<decimal> REMAIN_PRICE { get; set; }
        public string payment_status { get; set; }
        public string payment_method { get; set; }
        public Nullable<decimal> ShippmentCost { get; set; }
        public System.DateTime purchase_date { get; set; }
        public Nullable<int> reference_No { get; set; }
        public string Store_name { get; set; }
        public string supplier_name { get; set; }
    }
}
