//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace purchasesPMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PURCHASES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_PURCHASES()
        {
            this.Purchase_Items = new HashSet<Purchase_Items>();
        }
    
        public int purchase_id { get; set; }
        public int store_Id { get; set; }
        public Nullable<int> reference_No { get; set; }
        public System.DateTime purchase_date { get; set; }
        public Nullable<decimal> ShippmentCost { get; set; }
        public string payment_method { get; set; }
        public string payment_status { get; set; }
        public Nullable<decimal> REMAIN_PRICE { get; set; }
        public Nullable<decimal> TOTAL_PAIED { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public int CURR_ID { get; set; }
        public int SUPP_ID { get; set; }
        public string purchase_status { get; set; }
        public string purchase_Notes { get; set; }
        public string payment_Notes { get; set; }
        public decimal tax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_Items> Purchase_Items { get; set; }
        public virtual TB_CURRENCIES TB_CURRENCIES { get; set; }
        public virtual TB_STORES TB_STORES { get; set; }
        public virtual TB_SUPPLIERS TB_SUPPLIERS { get; set; }
    }
}
