//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace purchasesPMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_STOCKS
    {
        public int store_id { get; set; }
        public int prod_id { get; set; }
        public decimal quantity { get; set; }
        public string stock_Type { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string username { get; set; }
        public Nullable<int> supplier_Id { get; set; }
    
        public virtual TB_PRODUCTS TB_PRODUCTS { get; set; }
        public virtual TB_STORES TB_STORES { get; set; }
        public virtual TB_STOCKS TB_STOCKS1 { get; set; }
        public virtual TB_STOCKS TB_STOCKS2 { get; set; }
    }
}
